BBBBBBB BBBBBBBBBBBB
BBBBB BBBBBXXBBBBBBBB
BBBBB BBBBBB
    XXXX XXXXXXXXX XXXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            BBBBBBBBBB
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXX
    XXXXXX
    XXXXXX
BBBBBBBB