BBBBBBB BBBBBBBBBBBB
BBBBB BBBBBXXBBBBBBBB
BBBBB BBBBBB
    XXXX XXXXXXXXX XXXXXXXXXXX
    BBB BBBBBBB BB BBBBBBBBBBBB
    XXXX XXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXX
            XX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXX
        XXXXXX
    XXXXXX
    BBBBBB
    XXXXXX
BBBBBBBB