BBBBBBB BBBBBBBBBBBB
BBBBB BBBBBXXBBBBBBBB
BBBBB BBBBBB
    XXXX XXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXX  XXXXXXXXX
        XXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXX XXXXXXX XXXXXXX XXXXXX

            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB
