# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20170405_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landnum',
            old_name='land_num',
            new_name='num',
        ),
    ]
