# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('asset', '0005_auto_20170405_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandOwner',
            fields=[
            ],
            options={
                'verbose_name': '田地所属于人信息',
                'verbose_name_plural': '田地所属于人信息',
                'proxy': True,
            },
            bases=('account.people',),
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': '原所属人田地明细', 'verbose_name_plural': '原所属人田地明细'},
        ),
    ]
