# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20170406_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land', to='account.People', verbose_name='所属人'),
        ),
    ]
