# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20170406_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='所属人'),
        ),
    ]
