# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='户名号码')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '户口号码',
                'verbose_name_plural': '户口号码',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=8, verbose_name='姓氏')),
                ('last_name', models.CharField(max_length=12, verbose_name='名字')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='性别')),
                ('id_card_num', models.CharField(blank=True, db_index=True, max_length=18, null=True, verbose_name='身份证号码')),
                ('is_main', models.BooleanField(default=False, verbose_name='是否为户主')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('is_marry', models.BooleanField(default=False, verbose_name='是否已婚')),
                ('is_getmoney', models.BooleanField(default=False, verbose_name='分钱资格')),
                ('joind', models.DateField(verbose_name='入户日期')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='account.Account', verbose_name='所属户口')),
            ],
            options={
                'verbose_name': '村民信息',
                'verbose_name_plural': '村民信息',
            },
        ),
    ]
