# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_people_is_del'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='account_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='户口类型'),
        ),
        migrations.AddField(
            model_name='people',
            name='education',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='教育程度'),
        ),
        migrations.AddField(
            model_name='people',
            name='nationality',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='民族'),
        ),
        migrations.AddField(
            model_name='people',
            name='phone_num',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='电话号码'),
        ),
    ]
