# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170401_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='joind',
            field=models.DateField(blank=True, null=True, verbose_name='入户日期'),
        ),
    ]
