# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170402_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='account.Account', verbose_name='所属户口'),
        ),
    ]
