# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livingcost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerwater',
            name='mark_d',
            field=models.DateField(verbose_name='抄表日期'),
        ),
    ]
