# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livingcost', '0002_auto_20170403_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterrate',
            options={'get_latest_by': 'mark_d', 'ordering': ['-mark_d'], 'verbose_name': '水费', 'verbose_name_plural': '水费'},
        ),
        migrations.RemoveField(
            model_name='centerwater',
            name='m3',
        ),
        migrations.RemoveField(
            model_name='waterrate',
            name='m3',
        ),
        migrations.AddField(
            model_name='centerwater',
            name='is_post',
            field=models.BooleanField(default=False, verbose_name='发布'),
        ),
        migrations.AddField(
            model_name='centerwater',
            name='meter_num',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='水表度数'),
        ),
        migrations.AddField(
            model_name='waterrate',
            name='meter_num',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='水表度数'),
            preserve_default=False,
        ),
    ]
