BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBBXXXXXBBBBBBBBXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX
XXXXXX
XXXXXXXXXXX
    XXXX XXXXXXXXX XXXXXX
        XX XXXXXXXX XXXXXXXXXXXXX
            XX
        XXXX
        XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXX
XXXXXBBBBB BBBBBBBBBBBBBBXXXXXX
XXXXXXX

XXXXXXX
XXXXXXX